export const consonants = [
  {
    position: 1,
    letter: 'ก',
    transription: 'кᴐ:',
    associative_word: 'ไก่',
    associative_word_transcription: 'кай',
    associative_word_translate: 'курица',
  },
  {
    position: 2,
    letter: 'ข',
    transription: 'кхᴐ:ˇ',
    associative_word: 'ไข่',
    associative_word_transcription: 'кхай`',
    associative_word_translate: 'яйцо',
  },
  {
    position: 3,
    letter: 'ฃ',
    transription: 'кхᴐ:ˇ',
    associative_word: 'ขวด',
    associative_word_transcription: 'кху:ат`',
    associative_word_translate: 'бутылка',
  },
  {
    position: 4,
    letter: 'ค',
    transription: 'кхᴐ:',
    associative_word: 'ควาย',
    associative_word_transcription: 'кхва:й',
    associative_word_translate: 'буйвол',
  },
  {
    position: 5,
    letter: 'ฅ',
    transription: 'кхᴐ',
    associative_word: 'คน',
    associative_word_transcription: 'кхон',
    associative_word_translate: 'человек',
  },
  {
    position: 6,
    letter: 'ฆ',
    transription: 'кхᴐ:',
    associative_word: 'ระฆัง',
    associative_word_transcription: 'раˊкханг',
    associative_word_translate: 'колокол',
  },
  {
    position: 7,
    letter: 'ง',
    transription: 'нгᴐ:',
    associative_word: 'งู',
    associative_word_transcription: 'нгу:',
    associative_word_translate: 'змея',
  },
  {
    position: 8,
    letter: 'จ',
    transription: 'тьᴐ:',
    associative_word: 'จาน',
    associative_word_transcription: 'тьа:н',
    associative_word_translate: 'тарелка',
  },
  {
    position: 9,
    letter: 'ฉ',
    transription: 'чхᴐ:ˇ',
    associative_word: 'ฉิ่ง',
    associative_word_transcription: 'чхингˋ',
    associative_word_translate: 'тарелки',
  },
  {
    position: 10,
    letter: 'ช',
    transription: 'чхᴐ:',
    associative_word: 'ช้าง',
    associative_word_transcription: 'чха:нгˊ',
    associative_word_translate: 'слон',
  },
  {
    position: 11,
    letter: 'ซ',
    transription: 'сᴐ:',
    associative_word: 'โซ่',
    associative_word_transcription: 'co:ˆ',
    associative_word_translate: 'цепь',
  },
  {
    position: 12,
    letter: 'ฌ',
    transription: 'чхᴐ:',
    associative_word: 'เฌอ',
    associative_word_transcription: 'чхә:',
    associative_word_translate: 'дерево',
  },
  {
    position: 13,
    letter: 'ญ',
    transription: 'йᴐ:',
    associative_word: 'หญิง',
    associative_word_transcription: 'йингˇ',
    associative_word_translate: 'женщина',
  },
  {
    position: 14,
    letter: 'ฎ',
    transription: 'дᴐ:',
    associative_word: 'ชฎา',
    associative_word_transcription: 'чхаˊда:',
    associative_word_translate: 'тайский головной убор',
  },
  {
    position: 15,
    letter: 'ฏ',
    transription: 'тᴐ:',
    associative_word: 'ปฏัก',
    associative_word_transcription: 'па`так`',
    associative_word_translate: 'копье',
  },
  {
    position: 16,
    letter: 'ฐ',
    transription: 'тхᴐ:ˇ',
    associative_word: 'ฐาน',
    associative_word_transcription: 'тха:нˇ',
    associative_word_translate: 'пьедестал',
  },
  {
    position: 17,
    letter: 'ฑ',
    transription: 'тхᴐ:',
    associative_word: 'มณโฑ',
    associative_word_transcription: 'мон тхо:',
    associative_word_translate: 'имя героини эпоса Ра',
  },
  {
    position: 18,
    letter: 'ฒ',
    transription: 'тхᴐ:',
    associative_word: 'ผู้เฒ่า',
    associative_word_transcription: 'пху:ˆтхауˆ',
    associative_word_translate: 'старик',
  },
  {
    position: 19,
    letter: 'ณ',
    transription: 'нᴐ:',
    associative_word: 'เณร',
    associative_word_transcription: 'нен',
    associative_word_translate: 'буддийский послушник',
  },
  {
    position: 20,
    letter: 'ด',
    transription: 'дᴐ:',
    associative_word: 'เด็ก',
    associative_word_transcription: 'декˋ',
    associative_word_translate: 'ребенок',
  },
  {
    position: 21,
    letter: 'ต',
    transription: 'тᴐ:',
    associative_word: 'เต่า',
    associative_word_transcription: 'тау',
    associative_word_translate: 'черепаха',
  },
  {
    position: 22,
    letter: 'ถ',
    transription: 'тхᴐ:ˇ',
    associative_word: 'ถุง',
    associative_word_transcription: 'тхунгˇ',
    associative_word_translate: 'мешок',
  },
  {
    position: 23,
    letter: 'ท',
    transription: 'тхᴐ:ˇ',
    associative_word: 'ทหาร',
    associative_word_transcription: 'тха:нˇ',
    associative_word_translate: 'солдат',
  },
  {
    position: 24,
    letter: 'ธ',
    transription: 'тхᴐ:',
    associative_word: 'ธง',
    associative_word_transcription: 'тхонг',
    associative_word_translate: 'флаг',
  },
  {
    position: 25,
    letter: 'หนู',
    transription: 'нᴐ:',
    associative_word: 'หนู',
    associative_word_transcription: 'ну:ˇ',
    associative_word_translate: 'мышь',
  },
  {
    position: 26,
    letter: 'บ',
    transription: 'бᴐ:',
    associative_word: 'ใบไม้',
    associative_word_transcription: 'бай майˊ',
    associative_word_translate: 'лист дерева',
  },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
  // {
  //   position: 1,
  //   letter: 'ก',
  //   transription: 'ко:',
  //   associative_word: 'string',
  //   associative_word_transcription: 'string',
  //   associative_word_translate: 'string',
  // },
];
